/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Emergentes;

import BaseDatos.Mysql;
import com.sun.glass.events.KeyEvent;
import javax.swing.ImageIcon;
import objetos.Platillo;
import tipografia.Fuentes;

/**
 *
 * @author isaac
 */
public class AgregarPlato extends javax.swing.JDialog {

    /**
     * Creates new form Inserta
     */
    private Fuentes tipograf = new Fuentes();
    private GenerarId generaid = new GenerarId();
    private Platillo plato;
    private Mysql mysql = new Mysql();

            
    public AgregarPlato(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setSize(600,400);
        setIconImage(new ImageIcon(getClass().getResource("../imagenes/LogoSolo.png")).getImage());
        estilos();
        lblId2.setText(generaid.generarIdPlato());
    }
    
    public boolean respuesta()
    {
        return true;
    }
    
    public void estilos()
    {
        lbltitle.setFont(tipograf.fuente(tipograf.monserratSemiBold, 1, 32));
        lblNombre.setFont(tipograf.fuente(tipograf.pragatiNarrowRegular, 0, 18));
        lblFirts.setFont(tipograf.fuente(tipograf.pragatiNarrowRegular, 0, 18));
        lblId2.setFont(tipograf.fuente(tipograf.pragatiNarrowRegular, 0, 18));
        lblId.setFont(tipograf.fuente(tipograf.pragatiNarrowRegular, 0, 18));
        
        btnAgregar.setFont(tipograf.fuente(tipograf.pragatiNarrowRegular, 1, 18));
        btnCancelar.setFont(tipograf.fuente(tipograf.pragatiNarrowRegular, 1, 18));
        
        txtPrecio.setFont(tipograf.fuente(tipograf.pragatiNarrowRegular, 0, 16));
        txtNombre.setFont(tipograf.fuente(tipograf.pragatiNarrowRegular, 0, 16));
        
        lblError.setFont(tipograf.fuente(tipograf.pragatiNarrowRegular, 1, 20));
        lblError.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cabecera = new javax.swing.JPanel();
        lbltitle = new javax.swing.JLabel();
        body = new javax.swing.JPanel();
        lblId = new javax.swing.JLabel();
        lblId2 = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new rscomponentshade.RSTextFieldShade();
        lblFirts = new javax.swing.JLabel();
        txtPrecio = new rscomponentshade.RSTextFieldShade();
        jPanel1 = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        cabecera.setBackground(new java.awt.Color(255, 255, 255));
        cabecera.setPreferredSize(new java.awt.Dimension(750, 60));

        lbltitle.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbltitle.setForeground(new java.awt.Color(181, 8, 37));
        lbltitle.setText("Agregar Platillo");
        cabecera.add(lbltitle);

        getContentPane().add(cabecera, java.awt.BorderLayout.PAGE_START);

        body.setBackground(new java.awt.Color(255, 255, 255));

        lblId.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblId.setText("Id Platillo");

        lblId2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblId2.setText("IDxxxxxxxx");

        lblNombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNombre.setText("Nombre Platillo");

        txtNombre.setBgShadeHover(new java.awt.Color(191, 141, 0));
        txtNombre.setPlaceholder("");
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });

        lblFirts.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblFirts.setText("Precio");

        txtPrecio.setBgShadeHover(new java.awt.Color(191, 141, 0));
        txtPrecio.setPlaceholder("");
        txtPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioKeyTyped(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 50, 5));

        btnAgregar.setBackground(new java.awt.Color(181, 8, 37));
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setText("Agregar");
        btnAgregar.setPreferredSize(new java.awt.Dimension(150, 40));
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregar);

        btnCancelar.setBackground(new java.awt.Color(181, 8, 37));
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.setPreferredSize(new java.awt.Dimension(150, 40));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        lblError.setForeground(new java.awt.Color(181, 8, 37));
        lblError.setText("Mensajes de error");
        jPanel2.add(lblError);

        javax.swing.GroupLayout bodyLayout = new javax.swing.GroupLayout(body);
        body.setLayout(bodyLayout);
        bodyLayout.setHorizontalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(bodyLayout.createSequentialGroup()
                .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bodyLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(lblId)
                        .addGap(134, 134, 134)
                        .addComponent(lblId2))
                    .addGroup(bodyLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombre)
                            .addGroup(bodyLayout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(lblFirts)))
                        .addGap(52, 52, 52)
                        .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        bodyLayout.setVerticalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId2)
                    .addComponent(lblId))
                .addGap(26, 26, 26)
                .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFirts)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        getContentPane().add(body, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
       
        if(txtNombre.getText().isEmpty() || txtPrecio.getText().isEmpty() )
        {
            lblError.setVisible(true);
            lblError.setText("Error de campos vacíos");
        }
        else
        {
            lblError.setVisible(false);
               
            plato = new Platillo(lblId2.getText(), txtNombre.getText(), Float.parseFloat(txtPrecio.getText()));
            mysql.conectar();
            mysql.insertaPlatillo(plato);
            mysql.desconectar();
            dispose();
            
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void txtPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioKeyTyped
        char caracter = evt.getKeyChar();
        
       if(Character.isLetter(caracter) || caracter == KeyEvent.VK_SPACE  || caracter==',' || (caracter == '.' && txtPrecio.getText().length()==0))
        {
            getToolkit().beep();
            evt.consume();
        }
        else 
       {
            if(txtPrecio.getText().contains(".") && caracter == '.')
            {
                evt.consume();
            }
       }
       
       lblError.setVisible(false);
    }//GEN-LAST:event_txtPrecioKeyTyped

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();
        
       if(txtNombre.getText().length() == 28 || caracter==',')
        {
            getToolkit().beep();
            evt.consume();
        }
       lblError.setVisible(false);
    }//GEN-LAST:event_txtNombreKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarPlato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarPlato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarPlato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarPlato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AgregarPlato dialog = new AgregarPlato(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel body;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JPanel cabecera;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblFirts;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblId2;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lbltitle;
    private rscomponentshade.RSTextFieldShade txtNombre;
    private rscomponentshade.RSTextFieldShade txtPrecio;
    // End of variables declaration//GEN-END:variables
}
