/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sesion;

import BaseDatos.Mysql;
import cafeteria.InicioAdmin;
import cafeteria.InicioCajero;
import java.awt.Color;
import java.awt.Frame;
import java.awt.Window;
import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;
import objetos.Empleado;
import tipografia.Fuentes;

/**
 *
 * @author isaac
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */

    private Mysql mysql = new Mysql();
    private Empleado empleado = new Empleado();
    private Fuentes fuente = new Fuentes();
    private Recuperar recuperar;
    private InicioCajero cajero;
    
    private InicioAdmin admin;
    
    public Login() {
        initComponents();
        setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("../imagenes/LogoSolo.png")).getImage());
        estilos();
    }
    
    public void estilos()
    {
        lblTitle.setFont(fuente.fuente(fuente.monserratSemiBold, 1, 45));
        lblTitle.setForeground(new Color(181,8,37));
        lblTitle.requestFocus();
        
        lblError.setVisible(false);
       
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelImagen = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelLogin = new javax.swing.JPanel();
        norte = new javax.swing.JPanel();
        sur = new javax.swing.JPanel();
        lado = new javax.swing.JPanel();
        centro = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        txtUser = new rscomponentshade.RSTextFieldShade();
        txtPass = new rscomponentshade.RSPassFieldShade();
        btnLogin = new javax.swing.JButton();
        lblLinker = new javax.swing.JLabel();
        lblError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        panelImagen.setBackground(new java.awt.Color(255, 255, 255));
        panelImagen.setPreferredSize(new java.awt.Dimension(500, 600));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sesion/coffee.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(500, 600));
        jLabel1.setMinimumSize(new java.awt.Dimension(500, 600));
        jLabel1.setPreferredSize(new java.awt.Dimension(500, 600));

        javax.swing.GroupLayout panelImagenLayout = new javax.swing.GroupLayout(panelImagen);
        panelImagen.setLayout(panelImagenLayout);
        panelImagenLayout.setHorizontalGroup(
            panelImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImagenLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelImagenLayout.setVerticalGroup(
            panelImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImagenLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(panelImagen, java.awt.BorderLayout.LINE_START);

        panelLogin.setBackground(new java.awt.Color(255, 255, 255));
        panelLogin.setLayout(new java.awt.BorderLayout());

        norte.setBackground(new java.awt.Color(255, 255, 255));
        norte.setPreferredSize(new java.awt.Dimension(400, 50));

        javax.swing.GroupLayout norteLayout = new javax.swing.GroupLayout(norte);
        norte.setLayout(norteLayout);
        norteLayout.setHorizontalGroup(
            norteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        norteLayout.setVerticalGroup(
            norteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        panelLogin.add(norte, java.awt.BorderLayout.PAGE_START);

        sur.setBackground(new java.awt.Color(255, 255, 255));
        sur.setPreferredSize(new java.awt.Dimension(400, 50));

        javax.swing.GroupLayout surLayout = new javax.swing.GroupLayout(sur);
        sur.setLayout(surLayout);
        surLayout.setHorizontalGroup(
            surLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        surLayout.setVerticalGroup(
            surLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        panelLogin.add(sur, java.awt.BorderLayout.PAGE_END);

        lado.setBackground(new java.awt.Color(255, 255, 255));
        lado.setPreferredSize(new java.awt.Dimension(50, 450));

        javax.swing.GroupLayout ladoLayout = new javax.swing.GroupLayout(lado);
        lado.setLayout(ladoLayout);
        ladoLayout.setHorizontalGroup(
            ladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        ladoLayout.setVerticalGroup(
            ladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        panelLogin.add(lado, java.awt.BorderLayout.LINE_END);

        centro.setBackground(new java.awt.Color(255, 255, 255));

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoVertical.png"))); // NOI18N

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lblTitle.setText("Iniciar Sesión");

        txtUser.setBgShadeHover(new java.awt.Color(191, 141, 0));
        txtUser.setPlaceholder("Usuario");

        txtPass.setBgShadeHover(new java.awt.Color(191, 141, 0));
        txtPass.setPlaceholder("Contraseña");

        btnLogin.setBackground(new java.awt.Color(131, 8, 37));
        btnLogin.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Aceptar");
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLoginMouseExited(evt);
            }
        });
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        lblLinker.setForeground(new java.awt.Color(153, 153, 153));
        lblLinker.setText("Recuperar contraseña");
        lblLinker.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLinker.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLinkerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLinkerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblLinkerMouseExited(evt);
            }
        });

        lblError.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblError.setForeground(new java.awt.Color(131, 8, 37));
        lblError.setText("Error en las credenciales de acceso");

        javax.swing.GroupLayout centroLayout = new javax.swing.GroupLayout(centro);
        centro.setLayout(centroLayout);
        centroLayout.setHorizontalGroup(
            centroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(centroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(centroLayout.createSequentialGroup()
                        .addComponent(lblTitle)
                        .addContainerGap(57, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, centroLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblLogo)
                        .addGap(124, 124, 124))))
            .addGroup(centroLayout.createSequentialGroup()
                .addGroup(centroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(centroLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(centroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(centroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtUser, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                                .addComponent(txtPass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(centroLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(lblLinker))
                    .addGroup(centroLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(lblError)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        centroLayout.setVerticalGroup(
            centroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centroLayout.createSequentialGroup()
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTitle)
                .addGap(30, 30, 30)
                .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblLinker)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(lblError)
                .addContainerGap())
        );

        panelLogin.add(centro, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelLogin, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        if(mysql.iniciar_sesion(txtUser.getText(), txtPass.getText())== true)
        {
            empleado = mysql.get1empelado(txtUser.getText());
            mysql.desconectar();
            if(empleado.getCargo().equals("Administrador"))
            {   
                admin = new InicioAdmin(empleado.getNumeroEmpleado());
                admin.setVisible(true);
                this.dispose();
            }
            else if(empleado.getCargo().equals("Cajero"))
            {
                cajero = new InicioCajero(empleado.getNumeroEmpleado());
                cajero.setVisible(true);
                this.dispose();
            }
        }
        else
        {
            lblError.setVisible(true);
        }
        mysql.desconectar();
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseEntered
        // TODO add your handling code here:
        btnLogin.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_btnLoginMouseEntered

    private void btnLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseExited
        // TODO add your handling code here:
        btnLogin.setBackground(new Color(181,8,37));
    }//GEN-LAST:event_btnLoginMouseExited

    private void lblLinkerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLinkerMouseExited
        // TODO add your handling code here:
        lblLinker.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_lblLinkerMouseExited

    private void lblLinkerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLinkerMouseEntered
        // TODO add your handling code here:
        lblLinker.setForeground(new Color(181,8,37));
    }//GEN-LAST:event_lblLinkerMouseEntered

    private void lblLinkerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLinkerMouseClicked
        // TODO add your handling code here:
        txtPass.setText("");
        txtUser.setText("");
        Window parentWindow = SwingUtilities.windowForComponent(this);
        Frame parentframe = null;
        if(parentWindow instanceof Frame)
        {
            parentframe = (Frame)parentWindow;
        }
        recuperar = new Recuperar(parentframe, true);
        recuperar.setVisible(true);
    }//GEN-LAST:event_lblLinkerMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JPanel centro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel lado;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblLinker;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel norte;
    private javax.swing.JPanel panelImagen;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JPanel sur;
    private rscomponentshade.RSPassFieldShade txtPass;
    private rscomponentshade.RSTextFieldShade txtUser;
    // End of variables declaration//GEN-END:variables
}
