/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cafeteria;

import BaseDatos.Mysql;
import Emergentes.DosBotones;
import Emergentes.EditaEmpleados;
import Emergentes.Inserta;
import Emergentes.UnBoton;
import Sesion.Login;
import java.awt.Color;
import java.awt.Frame;
import java.awt.Window;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import objetos.Empleado;
import tipografia.Fuentes;

/**
 *
 * @author isaac
 */



public class AdminEmpleados extends javax.swing.JFrame {

    /** 
     * Creates new form InicioAdmin
     */
    private Fuentes tipografia = new Fuentes();
    private Inserta insertar;
    private Mysql mysql = new Mysql();
    private Empleado empleado = new Empleado();
    private List <Empleado> listaEmpleado = new ArrayList<>();
    private String EmpleadoString, idSelect="";
    private EditaEmpleados editaEmp;
    private UnBoton unboton;
    private DosBotones dosBotones;
    
    private InicioAdmin regresa;
    
    DefaultTableModel modelo = new DefaultTableModel(){
        @Override
        public boolean isCellEditable(int filas, int columnas) {
            if(columnas == 5)
            {
                return true;
            }
            else
            {
                return false;
            }
        }
    };

    public void tablaLlena (String emp)
    {
        listaEmpleado.clear();
        modelo.setRowCount(0);
        modelo.setColumnIdentifiers(new Object[]{"Numero Empleado","Nombre", "Primer Apellido", "Segundo Apellido", "Cargo"});
        mysql.conectar();
        listaEmpleado = mysql.muestra(emp);
        mysql.desconectar();
        for(Empleado aux : listaEmpleado)
        {
            modelo.addRow(new Object[]{aux.getNumeroEmpleado(), aux.getNombre(), aux.getPrimerApellido(), aux.getSegundoApellido(), aux.getCargo()});
        }
        tblEmp.setModel(modelo);
    }
    
    public void tablaLlenaDinamic ()
    {
        listaEmpleado.clear();
        modelo.setRowCount(0);
        modelo.setColumnIdentifiers(new Object[]{"Numero Empleado","Nombre", "Primer Apellido", "Segundo Apellido", "Cargo"});
        mysql.conectar();
        listaEmpleado = mysql.muestraDinamica(EmpleadoString, txtsearch.getText());
        mysql.desconectar();
        for(Empleado aux : listaEmpleado)
        {
            modelo.addRow(new Object[]{aux.getNumeroEmpleado(), aux.getNombre(), aux.getPrimerApellido(), aux.getSegundoApellido(), aux.getCargo()});
        }
        tblEmp.setModel(modelo);
    }
    
    
    public AdminEmpleados(String emp) {
        initComponents();
        setSize(1200,600);
        setLocationRelativeTo(null);
        estilos();
        setIconImage(new ImageIcon(getClass().getResource("../imagenes/LogoSolo.png")).getImage());
        tablaLlena(emp);
        EmpleadoString = emp;
        btnRetroceder.requestFocus();
    }
    
    public void estilos()
    {
        tblEmp.getTableHeader().setOpaque(false);
        tblEmp.setFuenteFilas(tipografia.fuente(tipografia.pragatiNarrowRegular, 0, 18));
        tblEmp.setFuenteFilasSelect(tipografia.fuente(tipografia.pragatiNarrowRegular, 1, 18));
        tblEmp.setFuenteHead(tipografia.fuente(tipografia.monserratMedium, 1, 12));
        
        txtsearch.setFont(tipografia.fuente(tipografia.pragatiNarrowRegular, 0, 22));
        btnElimina.setFont(tipografia.fuente(tipografia.pragatiNarrowRegular, 1, 18));
        btnInserta.setFont(tipografia.fuente(tipografia.pragatiNarrowRegular, 1, 18));
        btnRetroceder.setFont(tipografia.fuente(tipografia.pragatiNarrowRegular, 1, 16));
    }

    private AdminEmpleados() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        norte = new javax.swing.JPanel();
        sur = new javax.swing.JPanel();
        derecha = new javax.swing.JPanel();
        izquierda = new javax.swing.JPanel();
        centro = new javax.swing.JPanel();
        cabecera = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmp = new rojerusan.RSTableMetro();
        btnElimina = new javax.swing.JButton();
        btnInserta = new javax.swing.JButton();
        btnRetroceder = new javax.swing.JButton();
        txtsearch = new rscomponentshade.RSTextFieldShade();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        norte.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout norteLayout = new javax.swing.GroupLayout(norte);
        norte.setLayout(norteLayout);
        norteLayout.setHorizontalGroup(
            norteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        norteLayout.setVerticalGroup(
            norteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(norte, java.awt.BorderLayout.PAGE_START);

        sur.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout surLayout = new javax.swing.GroupLayout(sur);
        sur.setLayout(surLayout);
        surLayout.setHorizontalGroup(
            surLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        surLayout.setVerticalGroup(
            surLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(sur, java.awt.BorderLayout.PAGE_END);

        derecha.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout derechaLayout = new javax.swing.GroupLayout(derecha);
        derecha.setLayout(derechaLayout);
        derechaLayout.setHorizontalGroup(
            derechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        derechaLayout.setVerticalGroup(
            derechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        getContentPane().add(derecha, java.awt.BorderLayout.LINE_END);

        izquierda.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout izquierdaLayout = new javax.swing.GroupLayout(izquierda);
        izquierda.setLayout(izquierdaLayout);
        izquierdaLayout.setHorizontalGroup(
            izquierdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        izquierdaLayout.setVerticalGroup(
            izquierdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        getContentPane().add(izquierda, java.awt.BorderLayout.LINE_START);

        centro.setBackground(new java.awt.Color(204, 204, 204));
        centro.setLayout(new java.awt.BorderLayout());

        cabecera.setBackground(new java.awt.Color(255, 255, 255));

        lblTitulo.setFont(new java.awt.Font("Tahoma", 0, 65)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(181, 8, 37));
        lblTitulo.setText("Administrar Empleados");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoSolo1.png"))); // NOI18N

        javax.swing.GroupLayout cabeceraLayout = new javax.swing.GroupLayout(cabecera);
        cabecera.setLayout(cabeceraLayout);
        cabeceraLayout.setHorizontalGroup(
            cabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cabeceraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 333, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        cabeceraLayout.setVerticalGroup(
            cabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cabeceraLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(16, 16, 16))
        );

        centro.add(cabecera, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tblEmp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Numero Empleado", "Nombre", "Primer Apellido", "Segundo Apellido", "Cargo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblEmp.setColorBackgoundHead(new java.awt.Color(181, 8, 37));
        tblEmp.setColorBordeHead(new java.awt.Color(181, 8, 37));
        tblEmp.setColorFilasBackgound2(new java.awt.Color(255, 102, 102));
        tblEmp.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        tblEmp.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        tblEmp.setGridColor(new java.awt.Color(0, 0, 0));
        tblEmp.setGrosorBordeFilas(0);
        tblEmp.setGrosorBordeHead(0);
        tblEmp.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblEmp.setMultipleSeleccion(false);
        tblEmp.setShowHorizontalLines(false);
        tblEmp.setShowVerticalLines(false);
        tblEmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblEmpMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblEmp);

        btnElimina.setBackground(new java.awt.Color(181, 8, 37));
        btnElimina.setForeground(new java.awt.Color(255, 255, 255));
        btnElimina.setText("Eliminar Empleado");
        btnElimina.setPreferredSize(new java.awt.Dimension(115, 40));
        btnElimina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminaActionPerformed(evt);
            }
        });

        btnInserta.setBackground(new java.awt.Color(181, 8, 37));
        btnInserta.setForeground(new java.awt.Color(255, 255, 255));
        btnInserta.setText("Insertar Empleado");
        btnInserta.setPreferredSize(new java.awt.Dimension(115, 40));
        btnInserta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertaActionPerformed(evt);
            }
        });

        btnRetroceder.setBackground(new java.awt.Color(181, 8, 37));
        btnRetroceder.setForeground(new java.awt.Color(255, 255, 255));
        btnRetroceder.setText("Retroceder");
        btnRetroceder.setPreferredSize(new java.awt.Dimension(115, 40));
        btnRetroceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetrocederActionPerformed(evt);
            }
        });

        txtsearch.setBgShadeHover(new java.awt.Color(191, 141, 0));
        txtsearch.setPlaceholder("Buscar Empleado");
        txtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsearchKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtsearchKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRetroceder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnInserta, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(btnElimina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(52, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btnRetroceder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(33, Short.MAX_VALUE)
                        .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnInserta, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btnElimina, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))))
        );

        centro.add(jPanel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(centro, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtsearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchKeyTyped
        
    }//GEN-LAST:event_txtsearchKeyTyped

    private void btnInsertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertaActionPerformed
        // TODO add your handling code here:
        Window parentWindow = SwingUtilities.windowForComponent(this);
        Frame parentframe = null;
        if(parentWindow instanceof Frame)
        {
            parentframe = (Frame)parentWindow;
        }
        insertar = new Inserta(parentframe,true);
        insertar.setVisible(true);
        if(insertar.respuesta2())
        {
            tablaLlena(EmpleadoString);
            idSelect = "";
        }
        txtsearch.setText("");
    }//GEN-LAST:event_btnInsertaActionPerformed

    private void btnRetrocederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetrocederActionPerformed
        // TODO add your handling code here:
        regresa = new InicioAdmin(EmpleadoString);
        regresa.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnRetrocederActionPerformed

    private void tblEmpMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEmpMousePressed
        // TODO add your handling code here:
        idSelect = tblEmp.getValueAt(tblEmp.getSelectedRow(), 0).toString();
        empleado = listaEmpleado.get(tblEmp.getSelectedRow());
        if(evt.getClickCount()==2)
        {
            Window parentWindow = SwingUtilities.windowForComponent(this);
            Frame parentframe = null;
            if(parentWindow instanceof Frame)
            {
                parentframe = (Frame)parentWindow;
            }
            editaEmp = new EditaEmpleados(parentframe, true, empleado);
            editaEmp.setVisible(true);
            if(editaEmp.respuesta2())
            {
                tablaLlena(EmpleadoString);
                idSelect = "";
            }
            txtsearch.setText("");
        }
    }//GEN-LAST:event_tblEmpMousePressed

    private void btnEliminaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminaActionPerformed
        // TODO add your handling code here:
        Window parentWindow = SwingUtilities.windowForComponent(this);
        Frame parentframe = null;
        if(parentWindow instanceof Frame)
        {
            parentframe = (Frame)parentWindow;
        }
        if(idSelect.equals(""))
        {
            unboton = new UnBoton(parentframe, true, 3);
            unboton.setVisible(true);
        }
        else
        {
            dosBotones = new DosBotones(parentframe, true, 0, empleado);
            dosBotones.setVisible(true);
            if(dosBotones.exito())
            {
                tablaLlena(EmpleadoString);
                idSelect = "";
            }
        }
        txtsearch.setText("");
    }//GEN-LAST:event_btnEliminaActionPerformed

    private void txtsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchKeyReleased
        // TODO add your handling code here:
        tablaLlenaDinamic();
    }//GEN-LAST:event_txtsearchKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminEmpleados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnElimina;
    private javax.swing.JButton btnInserta;
    private javax.swing.JButton btnRetroceder;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel cabecera;
    private javax.swing.JPanel centro;
    private javax.swing.JPanel derecha;
    private javax.swing.JPanel izquierda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel norte;
    private javax.swing.JPanel sur;
    private rojerusan.RSTableMetro tblEmp;
    private rscomponentshade.RSTextFieldShade txtsearch;
    // End of variables declaration//GEN-END:variables
}
