/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cafeteria;

import BaseDatos.Mysql;
import Emergentes.AgregarPlato;
import Emergentes.DosBotones;
import Emergentes.EditaEmpleados;
import Emergentes.EditarPlato;
import Emergentes.Inserta;
import Emergentes.UnBoton;
import Sesion.Login;
import java.awt.Color;
import java.awt.Frame;
import java.awt.Window;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import objetos.Empleado;
import objetos.Platillo;
import tipografia.Fuentes;

/**
 *
 * @author isaac
 */



public class AdminMenu extends javax.swing.JFrame {

    /** 
     * Creates new form InicioAdmin
     */
    private Fuentes tipografia = new Fuentes();
    private Platillo platillo = new Platillo();
    private Mysql mysql = new Mysql();
    private List <Platillo> listaplatillos = new ArrayList<>();
    private String EmpleadoString, idSelect="";
    private UnBoton unboton;
    private DosBotones dosBotones;
    private InicioAdmin regresa;
    private AgregarPlato agrega;
    private EditarPlato edita;
    
    DefaultTableModel modelo = new DefaultTableModel(){
        @Override
        public boolean isCellEditable(int filas, int columnas) {
            if(columnas == 3)
            {
                return true;
            }
            else
            {
                return false;
            }
        }
    };

    public void tablaLlena ()
    {
        listaplatillos.clear();
        modelo.setRowCount(0);
        modelo.setColumnIdentifiers(new Object[]{"Id Platillo","Nombre", "Precio"});
        mysql.conectar();
        listaplatillos = mysql.muestraPlatillos();
        mysql.desconectar();
        for(Platillo aux : listaplatillos)
        {
            modelo.addRow(new Object[]{aux.getIdPlatillo(), aux.getNombrePlatillo(), aux.getPrecio()});
        }
        tblPlatillos.setModel(modelo);
    }
    
    public void tablaLlenaDinamic ()
    {
        listaplatillos.clear();
        modelo.setRowCount(0);
        modelo.setColumnIdentifiers(new Object[]{"Id Platillo","Nombre", "Precio"});
        mysql.conectar();
        listaplatillos = mysql.muestraPlatillosDinamic(txtsearch.getText());
        mysql.desconectar();
        for(Platillo aux : listaplatillos)
        {
            modelo.addRow(new Object[]{aux.getIdPlatillo(), aux.getNombrePlatillo(), aux.getPrecio()});
        }
        tblPlatillos.setModel(modelo);
    }
    
    
    public AdminMenu(String emp) {
        initComponents();
        setSize(1200,600);
        setLocationRelativeTo(null);
        estilos();
        setIconImage(new ImageIcon(getClass().getResource("../imagenes/LogoSolo.png")).getImage());
        tablaLlena();
        EmpleadoString = emp;
        btnRetroceder.requestFocus();
    }
    
    public void estilos()
    {
        tblPlatillos.getTableHeader().setOpaque(false);
        tblPlatillos.setFuenteFilas(tipografia.fuente(tipografia.pragatiNarrowRegular, 0, 18));
        tblPlatillos.setFuenteFilasSelect(tipografia.fuente(tipografia.pragatiNarrowRegular, 1, 18));
        tblPlatillos.setFuenteHead(tipografia.fuente(tipografia.monserratMedium, 1, 12));
        
        txtsearch.setFont(tipografia.fuente(tipografia.pragatiNarrowRegular, 0, 22));
        btnElimina.setFont(tipografia.fuente(tipografia.pragatiNarrowRegular, 1, 18));
        btnInserta.setFont(tipografia.fuente(tipografia.pragatiNarrowRegular, 1, 18));
        btnRetroceder.setFont(tipografia.fuente(tipografia.pragatiNarrowRegular, 1, 16));
    }

    private AdminMenu() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        norte = new javax.swing.JPanel();
        sur = new javax.swing.JPanel();
        derecha = new javax.swing.JPanel();
        izquierda = new javax.swing.JPanel();
        centro = new javax.swing.JPanel();
        cabecera = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnElimina = new javax.swing.JButton();
        btnInserta = new javax.swing.JButton();
        btnRetroceder = new javax.swing.JButton();
        txtsearch = new rscomponentshade.RSTextFieldShade();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPlatillos = new rojerusan.RSTableMetro();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1200, 600));
        setMinimumSize(new java.awt.Dimension(1200, 600));
        setPreferredSize(new java.awt.Dimension(1200, 600));
        setResizable(false);

        norte.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout norteLayout = new javax.swing.GroupLayout(norte);
        norte.setLayout(norteLayout);
        norteLayout.setHorizontalGroup(
            norteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        norteLayout.setVerticalGroup(
            norteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(norte, java.awt.BorderLayout.PAGE_START);

        sur.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout surLayout = new javax.swing.GroupLayout(sur);
        sur.setLayout(surLayout);
        surLayout.setHorizontalGroup(
            surLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        surLayout.setVerticalGroup(
            surLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(sur, java.awt.BorderLayout.PAGE_END);

        derecha.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout derechaLayout = new javax.swing.GroupLayout(derecha);
        derecha.setLayout(derechaLayout);
        derechaLayout.setHorizontalGroup(
            derechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        derechaLayout.setVerticalGroup(
            derechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 723, Short.MAX_VALUE)
        );

        getContentPane().add(derecha, java.awt.BorderLayout.LINE_END);

        izquierda.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout izquierdaLayout = new javax.swing.GroupLayout(izquierda);
        izquierda.setLayout(izquierdaLayout);
        izquierdaLayout.setHorizontalGroup(
            izquierdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        izquierdaLayout.setVerticalGroup(
            izquierdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 723, Short.MAX_VALUE)
        );

        getContentPane().add(izquierda, java.awt.BorderLayout.LINE_START);

        centro.setBackground(new java.awt.Color(204, 204, 204));
        centro.setLayout(new java.awt.BorderLayout());

        cabecera.setBackground(new java.awt.Color(255, 255, 255));

        lblTitulo.setFont(new java.awt.Font("Tahoma", 0, 65)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(191, 141, 0));
        lblTitulo.setText("Administrar Menu");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoSolo1.png"))); // NOI18N

        javax.swing.GroupLayout cabeceraLayout = new javax.swing.GroupLayout(cabecera);
        cabecera.setLayout(cabeceraLayout);
        cabeceraLayout.setHorizontalGroup(
            cabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cabeceraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 487, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        cabeceraLayout.setVerticalGroup(
            cabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cabeceraLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(16, 16, 16))
        );

        centro.add(cabecera, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnElimina.setBackground(new java.awt.Color(191, 141, 0));
        btnElimina.setForeground(new java.awt.Color(255, 255, 255));
        btnElimina.setText("Eliminar Platillo");
        btnElimina.setPreferredSize(new java.awt.Dimension(115, 40));
        btnElimina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminaActionPerformed(evt);
            }
        });

        btnInserta.setBackground(new java.awt.Color(191, 141, 0));
        btnInserta.setForeground(new java.awt.Color(255, 255, 255));
        btnInserta.setText("Insertar Platillo");
        btnInserta.setPreferredSize(new java.awt.Dimension(115, 40));
        btnInserta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertaActionPerformed(evt);
            }
        });

        btnRetroceder.setBackground(new java.awt.Color(191, 141, 0));
        btnRetroceder.setForeground(new java.awt.Color(255, 255, 255));
        btnRetroceder.setText("Retroceder");
        btnRetroceder.setPreferredSize(new java.awt.Dimension(115, 40));
        btnRetroceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetrocederActionPerformed(evt);
            }
        });

        txtsearch.setBgShadeHover(new java.awt.Color(191, 141, 0));
        txtsearch.setPlaceholder("Buscar Platillo");
        txtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsearchKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtsearchKeyTyped(evt);
            }
        });

        tblPlatillos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id Platillo", "Nombre Platillo", "Precio"
            }
        ));
        tblPlatillos.setColorBackgoundHead(new java.awt.Color(191, 141, 0));
        tblPlatillos.setColorBordeFilas(new java.awt.Color(255, 255, 255));
        tblPlatillos.setColorBordeHead(new java.awt.Color(191, 141, 0));
        tblPlatillos.setColorFilasBackgound2(new java.awt.Color(205, 180, 63));
        tblPlatillos.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        tblPlatillos.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        tblPlatillos.setGridColor(new java.awt.Color(255, 255, 255));
        tblPlatillos.setGrosorBordeFilas(0);
        tblPlatillos.setGrosorBordeHead(0);
        tblPlatillos.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblPlatillos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblPlatillosMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(tblPlatillos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 759, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnInserta, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnElimina, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRetroceder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(60, 60, 60))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(115, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRetroceder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnInserta, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnElimina, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(169, 169, 169))
        );

        centro.add(jPanel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(centro, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtsearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchKeyTyped
        
    }//GEN-LAST:event_txtsearchKeyTyped

    private void btnInsertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertaActionPerformed
        Window parentWindow = SwingUtilities.windowForComponent(this);
        Frame parentframe = null;
        if(parentWindow instanceof Frame)
        {
            parentframe = (Frame)parentWindow;
        }
        agrega = new AgregarPlato(parentframe, true);
        agrega.setVisible(true);
        if(agrega.respuesta())
        {
            tablaLlena();
        }
        txtsearch.setText("");
    }//GEN-LAST:event_btnInsertaActionPerformed

    private void btnRetrocederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetrocederActionPerformed
        // TODO add your handling code here:
        regresa = new InicioAdmin(EmpleadoString);
        regresa.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnRetrocederActionPerformed

    private void btnEliminaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminaActionPerformed
        Window parentWindow = SwingUtilities.windowForComponent(this);
        Frame parentframe = null;
        if(parentWindow instanceof Frame)
        {
            parentframe = (Frame)parentWindow;
        }
        if(idSelect.equals(""))
        {
            unboton = new UnBoton(parentframe, true, 4);
            unboton.setVisible(true);
        }
        else
        {
            dosBotones = new DosBotones(parentframe, true, 1, platillo);
            dosBotones.setVisible(true);
            if(dosBotones.exito())
            {
                tablaLlena();
                idSelect = "";
            }
        }
        txtsearch.setText("");
    }//GEN-LAST:event_btnEliminaActionPerformed

    private void txtsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchKeyReleased
        // TODO add your handling code here:
        tablaLlenaDinamic();
    }//GEN-LAST:event_txtsearchKeyReleased

    private void tblPlatillosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPlatillosMousePressed
        idSelect = tblPlatillos.getValueAt(tblPlatillos.getSelectedRow(), 0).toString();
        platillo = listaplatillos.get(tblPlatillos.getSelectedRow());
        if(evt.getClickCount() == 2)
        {
            Window parentWindow = SwingUtilities.windowForComponent(this);
            Frame parentframe = null;
            if(parentWindow instanceof Frame)
            {
                parentframe = (Frame)parentWindow;
            }
            edita = new EditarPlato(parentframe, true, platillo);
            edita.setVisible(true);
            if(edita.respuesta())
            {
                tablaLlena();
                idSelect = "";
            }
            txtsearch.setText("");
        }
    }//GEN-LAST:event_tblPlatillosMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnElimina;
    private javax.swing.JButton btnInserta;
    private javax.swing.JButton btnRetroceder;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel cabecera;
    private javax.swing.JPanel centro;
    private javax.swing.JPanel derecha;
    private javax.swing.JPanel izquierda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel norte;
    private javax.swing.JPanel sur;
    private rojerusan.RSTableMetro tblPlatillos;
    private rscomponentshade.RSTextFieldShade txtsearch;
    // End of variables declaration//GEN-END:variables
}
