/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cafeteria;

import BaseDatos.Mysql;
import Sesion.Login;
import java.awt.Color;
import javax.swing.ImageIcon;
import objetos.Empleado;
import tipografia.Fuentes;

/**
 *
 * @author isaac
 */

public class InicioCajero extends javax.swing.JFrame {

    /** 
     * Creates new form InicioAdmin
     */
    
    private Fuentes fuente;
    private DatosPersonales personal;
    private String empleado;
    private Login login = new Login();
    private Mysql mysql = new Mysql();
    
    private Ordenar ordena;
    
    public InicioCajero(String emp) {
        initComponents();
        setSize(1200,600);
        setLocationRelativeTo(null);
        
        setIconImage(new ImageIcon(getClass().getResource("../imagenes/LogoSolo.png")).getImage());
        

        empleado = emp;
        estilos();
        
        personal = new DatosPersonales(empleado);
        personal.setVisible(false);
        
        ordena = new Ordenar();
        ordena.setVisible(true);
        
        
        centro.add(ordena);
        centro.validate();
        
    }

    private InicioCajero() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    public void estilos()
    {
        lblOrdenar.setLocation(100, 200);
        fuente = new Fuentes();
        lblTitulo.setFont(fuente.fuente(fuente.monserratSemiBold, 0, 55));
        lblOrdenar.setFont(fuente.fuente(fuente.monserratRegular, 0, 21));
        lblEstatus.setFont(fuente.fuente(fuente.monserratRegular, 0, 21));
        lblPersonal.setFont(fuente.fuente(fuente.monserratRegular, 0, 21));
        lblCerrar.setFont(fuente.fuente(fuente.monserratRegular, 0, 21));
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        norte = new javax.swing.JPanel();
        sur = new javax.swing.JPanel();
        derecha = new javax.swing.JPanel();
        izquierda = new javax.swing.JPanel();
        centro = new javax.swing.JPanel();
        cabecera = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblOrdenar = new javax.swing.JLabel();
        lblEstatus = new javax.swing.JLabel();
        lblPersonal = new javax.swing.JLabel();
        lblCerrar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        norte.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout norteLayout = new javax.swing.GroupLayout(norte);
        norte.setLayout(norteLayout);
        norteLayout.setHorizontalGroup(
            norteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1273, Short.MAX_VALUE)
        );
        norteLayout.setVerticalGroup(
            norteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(norte, java.awt.BorderLayout.PAGE_START);

        sur.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout surLayout = new javax.swing.GroupLayout(sur);
        sur.setLayout(surLayout);
        surLayout.setHorizontalGroup(
            surLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1273, Short.MAX_VALUE)
        );
        surLayout.setVerticalGroup(
            surLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(sur, java.awt.BorderLayout.PAGE_END);

        derecha.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout derechaLayout = new javax.swing.GroupLayout(derecha);
        derecha.setLayout(derechaLayout);
        derechaLayout.setHorizontalGroup(
            derechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        derechaLayout.setVerticalGroup(
            derechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        getContentPane().add(derecha, java.awt.BorderLayout.LINE_END);

        izquierda.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout izquierdaLayout = new javax.swing.GroupLayout(izquierda);
        izquierda.setLayout(izquierdaLayout);
        izquierdaLayout.setHorizontalGroup(
            izquierdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        izquierdaLayout.setVerticalGroup(
            izquierdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        getContentPane().add(izquierda, java.awt.BorderLayout.LINE_START);

        centro.setBackground(new java.awt.Color(204, 204, 204));
        centro.setLayout(new java.awt.BorderLayout());

        cabecera.setBackground(new java.awt.Color(255, 255, 255));

        lblTitulo.setFont(new java.awt.Font("Tahoma", 0, 65)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(181, 8, 37));
        lblTitulo.setText("Ordenes");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoSolo1.png"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 30, 5));

        lblOrdenar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblOrdenar.setForeground(new java.awt.Color(131, 8, 37));
        lblOrdenar.setText("Ordenar");
        lblOrdenar.setToolTipText("");
        lblOrdenar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblOrdenar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOrdenarMouseClicked(evt);
            }
        });
        jPanel1.add(lblOrdenar);

        lblEstatus.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblEstatus.setForeground(new java.awt.Color(153, 153, 153));
        lblEstatus.setText("Estados de orden");
        lblEstatus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblEstatus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEstatusMouseClicked(evt);
            }
        });
        jPanel1.add(lblEstatus);

        lblPersonal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblPersonal.setForeground(new java.awt.Color(153, 153, 153));
        lblPersonal.setText("Datos Personales");
        lblPersonal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblPersonal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPersonalMouseClicked(evt);
            }
        });
        jPanel1.add(lblPersonal);

        lblCerrar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblCerrar.setForeground(new java.awt.Color(153, 153, 153));
        lblCerrar.setText("Cerrar Sesion");
        lblCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarMouseClicked(evt);
            }
        });
        jPanel1.add(lblCerrar);

        javax.swing.GroupLayout cabeceraLayout = new javax.swing.GroupLayout(cabecera);
        cabecera.setLayout(cabeceraLayout);
        cabeceraLayout.setHorizontalGroup(
            cabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cabeceraLayout.createSequentialGroup()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );
        cabeceraLayout.setVerticalGroup(
            cabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cabeceraLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(cabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cabeceraLayout.createSequentialGroup()
                        .addComponent(lblTitulo)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cabeceraLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))))
        );

        centro.add(cabecera, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(centro, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblOrdenarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOrdenarMouseClicked
        // Interfaz cabecera
        lblOrdenar.setForeground(new Color(131,8,37));
        lblPersonal.setForeground(new Color(137,137,137));
        lblEstatus.setForeground(new Color(137,137,137));
        lblCerrar.setForeground(new Color(137,137,137));
        
        personal.setVisible(false);
        
        ordena = new Ordenar();
        ordena.setVisible(true);
        
        
        centro.add(ordena);
        centro.validate();
        
    }//GEN-LAST:event_lblOrdenarMouseClicked

    private void lblEstatusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEstatusMouseClicked
        // TODO add your handling code here:
        lblOrdenar.setForeground(new Color(137,137,137));
        lblPersonal.setForeground(new Color(137,137,137));
        lblEstatus.setForeground(new Color(131,8,37));
        lblCerrar.setForeground(new Color(137,137,137));
        
        
        
    }//GEN-LAST:event_lblEstatusMouseClicked

    private void lblPersonalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPersonalMouseClicked
        // TODO add your handling code here:
        lblOrdenar.setForeground(new Color(137,137,137));
        lblPersonal.setForeground(new Color(131,8,37));
        lblEstatus.setForeground(new Color(137,137,137));
        lblCerrar.setForeground(new Color(137,137,137));

        ordena.setVisible(false);
       
        personal = new DatosPersonales(empleado);
        personal.setVisible(true);
        
        
        centro.add(personal);
        centro.validate();
        
    }//GEN-LAST:event_lblPersonalMouseClicked

    private void lblCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseClicked
        // TODO add your handling code here:
        lblOrdenar.setForeground(new Color(137,137,137));
        lblPersonal.setForeground(new Color(137,137,137));
        lblEstatus.setForeground(new Color(137,137,137));
        
        ordena.setVisible(false);
        personal.setVisible(false);
        
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblCerrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioCajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioCajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioCajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioCajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioCajero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel cabecera;
    private javax.swing.JPanel centro;
    private javax.swing.JPanel derecha;
    private javax.swing.JPanel izquierda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCerrar;
    private javax.swing.JLabel lblEstatus;
    private javax.swing.JLabel lblOrdenar;
    private javax.swing.JLabel lblPersonal;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel norte;
    private javax.swing.JPanel sur;
    // End of variables declaration//GEN-END:variables
}
